/**
 * Autogenerated by Thrift Compiler (1.0.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef otc_CONSTANTS_H
#define otc_CONSTANTS_H

#include "otc_types.h"



class otcConstants {
 public:
  otcConstants();

};

extern const otcConstants g_otc_constants;



#endif
